<?php
use Illuminate\Database\Seeder;
use App\Models\Admin\LotteryPlayer;

class LotteryPlayerTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	LotteryPlayer::truncate();

        LotteryPlayer::create([ 'name' => 'ALAN BURNS',  'telephone' => '',  'email' => '',  'lottery_number' => '1',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'PAUL SHEPHERD',  'telephone' => '07904954186',  'email' => 'paulrugbyref@aol.com',  'lottery_number' => '1',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'MRS I BALL',  'telephone' => '',  'email' => '',  'lottery_number' => '2',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'JANET LOWRY',  'telephone' => '',  'email' => '',  'lottery_number' => '2',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'CHRISTINA CHAMBERS',  'telephone' => '',  'email' => '',  'lottery_number' => '3',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'KATH EIRLYS WILLIAMS',  'telephone' => '01942733567',  'email' => 'katy.bear@live.co.uk',  'lottery_number' => '3',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'JOSHUA COFFEY',  'telephone' => '',  'email' => '',  'lottery_number' => '4',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'TINA ROUT',  'telephone' => '07947305930',  'email' => 'tinalrout@gmail.com',  'lottery_number' => '4',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'MIKE PARTRIDGE',  'telephone' => '07701017105',  'email' => 'michael.partridge4071@o2.co.uk',  'lottery_number' => '5',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'JANET WILSON',  'telephone' => '01514865631',  'email' => 'poppyjan@hotmail.com',  'lottery_number' => '5',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'DOREEN PARTRIDGE',  'telephone' => '0188438397',  'email' => '',  'lottery_number' => '6',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'ANNE HEATHERINGTON',  'telephone' => '07709170216',  'email' => 'cissyanne59@gmail.com',  'lottery_number' => '6',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'CRAIG TODD ',  'telephone' => '',  'email' => '',  'lottery_number' => '7',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'KATE HILL',  'telephone' => '',  'email' => '',  'lottery_number' => '7',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'MARK DANA-BRANDT',  'telephone' => '07956772718',  'email' => 'sharondana1@outlook.com',  'lottery_number' => '8',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'JANET LOWRY',  'telephone' => '',  'email' => '',  'lottery_number' => '8',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'SANDRA TODD',  'telephone' => '0188438888',  'email' => '',  'lottery_number' => '9',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'JANET WILSON',  'telephone' => '01514865631',  'email' => 'poppyjan@hotmail.com',  'lottery_number' => '9',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'JANICE DENNIS',  'telephone' => '',  'email' => 'jdennis1949@hotmail.co.uk',  'lottery_number' => '10',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'JANET BETLEY',  'telephone' => '07881917975',  'email' => 'janetsbetley@gmail.com',  'lottery_number' => '10',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'JULIE BYRNE',  'telephone' => '01392273332',  'email' => '',  'lottery_number' => '11',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'CLAIRE JOHNSON',  'telephone' => '07773556413',  'email' => 'claire-94@live.co.uk',  'lottery_number' => '11',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'SAMANTHA COFFEY',  'telephone' => '0188432943',  'email' => 'samanthacoffey39@gmail.com',  'lottery_number' => '12',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'CATH RIGBY',  'telephone' => '07835274148',  'email' => 'cathneedle@hotmail.co.uk',  'lottery_number' => '12',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'CHERYL HUMMING',  'telephone' => '0188434834',  'email' => 'a-hemming@sky.com',  'lottery_number' => '13',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'JANET LOWRY',  'telephone' => '',  'email' => '',  'lottery_number' => '13',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'GILL BARROW',  'telephone' => '07599339497',  'email' => 'gillianbarrow@talktalk.net',  'lottery_number' => '14',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'CHELLE BELLE',  'telephone' => '08572238820',  'email' => 'Michellemarling@hotmail.co.uk',  'lottery_number' => '14',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'NICOLA PHIPPS',  'telephone' => '078918833962',  'email' => 'nicnak-nik@hotmail.co.uk',  'lottery_number' => '15',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'JANET LOWRY',  'telephone' => '',  'email' => '',  'lottery_number' => '15',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => ' NIGEL COFFEY',  'telephone' => '01884266646',  'email' => 'coffeybean1966@hotmail.co.uk',  'lottery_number' => '16',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'CATH RIGBY',  'telephone' => '07835274148',  'email' => 'cathneedle@hotmail.co.uk',  'lottery_number' => '16',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'NINA BUTLER',  'telephone' => '0188434725',  'email' => '',  'lottery_number' => '17',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'ANN FEETENBY',  'telephone' => '01723581239',  'email' => 'annfeetenby@hotmail.com',  'lottery_number' => '17',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'JANICE DENNIS',  'telephone' => '',  'email' => '',  'lottery_number' => '18',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'TRACEY CHEESEMAN',  'telephone' => '07447596648',  'email' => 'tracey_1967@hotmail.com',  'lottery_number' => '18',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'LAU HARVEY',  'telephone' => '0 ',  'email' => '',  'lottery_number' => '19',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'DOT STONE EVERETT',  'telephone' => '',  'email' => '',  'lottery_number' => '19',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'MALCOLM SMITH',  'telephone' => '07966 087246',  'email' => 'mifffem@btinternet.com',  'lottery_number' => '20',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'JANET LOWRY',  'telephone' => '',  'email' => '',  'lottery_number' => '20',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'MAT NEWELL',  'telephone' => '07809261574',  'email' => 'mat710@hotmail.co.uk',  'lottery_number' => '21',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'FAYE McCABE',  'telephone' => '07591564389',  'email' => 'faye.mccabe@gmail.com',  'lottery_number' => '21',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'JUNE DODGE',  'telephone' => '',  'email' => 'jdennis1949@hotmail.co.uk',  'lottery_number' => '22',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'FAYE McCABE',  'telephone' => '07591564389',  'email' => 'faye.mccabe@gmail.com',  'lottery_number' => '22',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'HELEN BASTIN',  'telephone' => '0 ',  'email' => 'hnoades720@btinternet.com',  'lottery_number' => '23',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'DOT STONE EVERETT',  'telephone' => '',  'email' => '',  'lottery_number' => '23',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'KELLY EDWARDS',  'telephone' => '0188433960',  'email' => 'kje32@aol.com',  'lottery_number' => '24',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'ANNE HEATHERINGTON',  'telephone' => '07709170216',  'email' => 'cissyanne59@gmail.com',  'lottery_number' => '24',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'SIMON R PALMER',  'telephone' => '',  'email' => '',  'lottery_number' => '25',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'CAROL JONES',  'telephone' => '07891983812',  'email' => 'raymondglyn@btopenworld.com',  'lottery_number' => '25',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'SOPHIE ELLACOTT',  'telephone' => '',  'email' => '',  'lottery_number' => '26',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'FAYE McCABE',  'telephone' => '07591564389',  'email' => 'faye.mccabe@gmail.com',  'lottery_number' => '26',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'JUNE DODGE',  'telephone' => '0188432479',  'email' => 'jdennis1949@hotmail.co.uk',  'lottery_number' => '27',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'FAYE McCABE',  'telephone' => '',  'email' => 'faye.mccabe@gmail.com',  'lottery_number' => '27',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'MARK RADFORD',  'telephone' => '07974082726',  'email' => 'wiffy-squiffy@hotmail.com',  'lottery_number' => '28',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'ELAIN FAIRLEY',  'telephone' => '01606835535',  'email' => 'elainefairley@talktalk.net',  'lottery_number' => '28',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'MAT NEWELL',  'telephone' => '07809261574',  'email' => 'mat710@hotmail.co.uk',  'lottery_number' => '29',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'JOHN GARNETT',  'telephone' => '01512870803',  'email' => 'j-garnett@live.com',  'lottery_number' => '29',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'SHIRLEY BOYCE',  'telephone' => '',  'email' => '',  'lottery_number' => '30',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'JAN FULLARTON',  'telephone' => '07934204835',  'email' => 'janfullarton@hotlail.co.uk',  'lottery_number' => '30',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'MIKE PARTRIDGE',  'telephone' => '07701017105',  'email' => 'michael.partridge4071@o2.co.uk',  'lottery_number' => '31',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'JOHN GARNETT',  'telephone' => '01512870803',  'email' => 'j-garnett@live.com',  'lottery_number' => '31',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'LES MILLER',  'telephone' => '07702174383',  'email' => 'mildini@live.co.uk',  'lottery_number' => '32',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'ANNE HEATHERINGTON',  'telephone' => '07709170216',  'email' => 'cissyanne59@gmail.com',  'lottery_number' => '32',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'JOHN WALKER',  'telephone' => '0188435444',  'email' => '',  'lottery_number' => '33',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'AXEL FOLEY',  'telephone' => '',  'email' => 'axel@trenchartax.com',  'lottery_number' => '33',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'JUNE DODGE',  'telephone' => '',  'email' => '',  'lottery_number' => '34',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'ANN FEETENBY',  'telephone' => '01723581239',  'email' => 'annfeetenby@hotmail.com',  'lottery_number' => '34',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'MAT NEWELL',  'telephone' => '07809261574',  'email' => 'mat710@hotmail.co.uk',  'lottery_number' => '35',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'JOHN GARNETT',  'telephone' => '01512870803',  'email' => 'j-garnett@live.com',  'lottery_number' => '35',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'MIKE PARTRIDGE',  'telephone' => '07701017105',  'email' => 'michael.partridge4071@o2.co.uk',  'lottery_number' => '36',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'FAYE McCABE',  'telephone' => '',  'email' => 'faye.mccabe@gmail.com',  'lottery_number' => '36',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'VANESSA MILLAR',  'telephone' => '07784941719',  'email' => 'vanessa17@gmx.co.uk',  'lottery_number' => '37',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'JAN FULLARTON',  'telephone' => '07934204835',  'email' => '',  'lottery_number' => '37',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'PHILL & SUE RENDALL',  'telephone' => '',  'email' => '',  'lottery_number' => '38',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'JAN FULLARTON',  'telephone' => '07934204835',  'email' => '',  'lottery_number' => '38',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'RICKY BANFIELD',  'telephone' => '0188432614',  'email' => 'rick&kevin.banfield@gmail.com',  'lottery_number' => '39',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'APRIL LOCKETT',  'telephone' => '',  'email' => '',  'lottery_number' => '39',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'SHARON VAUGHAN',  'telephone' => '',  'email' => 'svaughan40@gmail.com',  'lottery_number' => '40',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'JOHN GARNETT',  'telephone' => '01512870803',  'email' => 'j-garnett@live.com',  'lottery_number' => '40',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'SHIRLEY BOYCE',  'telephone' => '',  'email' => '',  'lottery_number' => '41',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'DANIEL COFFEY',  'telephone' => '',  'email' => 'HEAVEN',  'lottery_number' => '41',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'MARGARET SIVITER',  'telephone' => '0188438658',  'email' => 'margaretsiviter@btinternet.com',  'lottery_number' => '42',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'JOHN GARNETT',  'telephone' => '01512870803',  'email' => 'j-garnett@live.com',  'lottery_number' => '42',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'MIKE PARTRIDGE',  'telephone' => '07701017105',  'email' => 'michael.partridge4071@o2.co.uk',  'lottery_number' => '43',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'PHIL LAMB',  'telephone' => '01933778166',  'email' => 'pllarrylamb47@gmail.com',  'lottery_number' => '43',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'DOTTYS CAFÉ',  'telephone' => '0188438080',  'email' => '',  'lottery_number' => '44',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'LYN RIGBY',  'telephone' => '07956254145',  'email' => 'Lynseville0912@hotmail.co.uk',  'lottery_number' => '44',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'CLAIRE RADFORD',  'telephone' => '07974082726',  'email' => 'wiffy-squiffy@hotmail.com',  'lottery_number' => '45',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'ANN FEETENBY',  'telephone' => '01723581239',  'email' => 'annfeetenby@hotmail.com',  'lottery_number' => '45',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'SARAH SHERGOLD',  'telephone' => '0188434169',  'email' => 'sara.shergold@hotmail.co.uk',  'lottery_number' => '46',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'GLYN JACKSON',  'telephone' => '01283212008',  'email' => 'glyn.jackson@tiscali.co.uk',  'lottery_number' => '46',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'RON PARTRIDGE',  'telephone' => '0188438397',  'email' => '',  'lottery_number' => '47',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'JUNE WALKER',  'telephone' => '',  'email' => '',  'lottery_number' => '47',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'CORAL RACING',  'telephone' => '01884839671',  'email' => '',  'lottery_number' => '48',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'JUNE WALKER',  'telephone' => '',  'email' => '',  'lottery_number' => '48',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'JANICE DENNIS',  'telephone' => '',  'email' => 'jdennis1949@hotmail.co.uk',  'lottery_number' => '49',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'ANN FEETENBY',  'telephone' => '01723581239',  'email' => 'annfeetenby@hotmail.com',  'lottery_number' => '49',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'MICHAEL ELLACOTT',  'telephone' => '',  'email' => '',  'lottery_number' => '50',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'ANDREA MADDOCKS',  'telephone' => '01252319939',  'email' => 'bpandammaddock@virginmedia.com',  'lottery_number' => '50',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'MAT NEWELL',  'telephone' => '07809261574',  'email' => 'mat710@hotmail.co.uk',  'lottery_number' => '51',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'PAMELA CRAWFORD',  'telephone' => '01613384351',  'email' => 't.yearn1812@btinternet.com',  'lottery_number' => '51',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'MIKE PARTRIDGE',  'telephone' => '07701017105',  'email' => 'michael.partridge4071@o2.co.uk',  'lottery_number' => '52',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'SALLY CRIPPS',  'telephone' => '02088944051',  'email' => 'sallycripps@sky.com',  'lottery_number' => '52',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'JOHN CHAMBERS',  'telephone' => '',  'email' => '',  'lottery_number' => '53',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'ANN FEETENBY',  'telephone' => '01723581239',  'email' => 'annfeetenby@hotmail.com',  'lottery_number' => '53',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'SARAH SHERGOLD',  'telephone' => '0188434169',  'email' => 'sara.shergold@hotmail.co.uk',  'lottery_number' => '54',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'ANN FEETENBY',  'telephone' => '01723581239',  'email' => 'annfeetenby@hotmail.com',  'lottery_number' => '54',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'DAVID GRAY',  'telephone' => '',  'email' => '',  'lottery_number' => '55',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'PAT IMRIE',  'telephone' => '07732261891',  'email' => 'sharoncrook70@yahoo.co.uk',  'lottery_number' => '55',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'ROY MARTIN',  'telephone' => '0188434406',  'email' => '',  'lottery_number' => '56',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'ANN FEETENBY',  'telephone' => '',  'email' => 'jonyvon@live.co.uk',  'lottery_number' => '56',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'JOSHUA COFFEY',  'telephone' => '',  'email' => '',  'lottery_number' => '57',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'PAT IMRIE',  'telephone' => '07732261891',  'email' => 'sharoncrook70@yahoo.co.uk',  'lottery_number' => '57',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'MRS S MARTIN',  'telephone' => '0188434406',  'email' => '',  'lottery_number' => '58',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'ANN FEETENBY',  'telephone' => '01723581239',  'email' => 'annfeetenby@hotmail.com',  'lottery_number' => '58',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'SAMANTHA LANE',  'telephone' => '07803484614',  'email' => '',  'lottery_number' => '59',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'KATE HILL',  'telephone' => '',  'email' => '',  'lottery_number' => '59',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'BRUNO',  'telephone' => '',  'email' => '',  'lottery_number' => '60',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'YVONNE SQUIRREL',  'telephone' => '',  'email' => 'annfeetenby@hotmail.com',  'lottery_number' => '60',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'IAN BONZO ATKINS',  'telephone' => '',  'email' => '',  'lottery_number' => '61',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'MAXINE CRAWFORD',  'telephone' => '',  'email' => '',  'lottery_number' => '61',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'HANNA WINTER',  'telephone' => '',  'email' => '',  'lottery_number' => '62',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'SANDRA COWIN',  'telephone' => '07842088745',  'email' => 'olwyn111@hotmail.co.uk',  'lottery_number' => '62',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'MRS W MILES',  'telephone' => '0188434406',  'email' => '',  'lottery_number' => '63',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'STACEY EVERETT',  'telephone' => '',  'email' => '',  'lottery_number' => '63',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'SUSAN SMITH',  'telephone' => '07966 087246',  'email' => 'mifffem@btinternet.com',  'lottery_number' => '64',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'LINDA SHAW',  'telephone' => '07745498789',  'email' => 'l.shaw65@btinternet.com',  'lottery_number' => '64',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'ILZE LAZDINA',  'telephone' => '07909241266',  'email' => '',  'lottery_number' => '65',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'PAT IMRIE',  'telephone' => '',  'email' => 'jonyvon@live.co.uk',  'lottery_number' => '65',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'DONNA',  'telephone' => '',  'email' => '',  'lottery_number' => '66',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'MEL ELLIOTT',  'telephone' => '',  'email' => '',  'lottery_number' => '66',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => ' JANET HOLMES',  'telephone' => '07811193595',  'email' => '',  'lottery_number' => '67',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'MEL ELLIOTT',  'telephone' => '',  'email' => '',  'lottery_number' => '67',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'RITA PALFREY',  'telephone' => '01884560383',  'email' => 'ritandavid@talktalk.net',  'lottery_number' => '68',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'PAT IMRIE',  'telephone' => '',  'email' => '',  'lottery_number' => '68',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'RITA PALFREY',  'telephone' => '01884560383',  'email' => 'ritandavid@talktalk.net',  'lottery_number' => '69',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'PAT IMRIE',  'telephone' => '',  'email' => '',  'lottery_number' => '69',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'SALLIE ALFORD',  'telephone' => '07525484248',  'email' => 'salalford66@yahoo.co.uk',  'lottery_number' => '70',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'JOHN SQUIRREL',  'telephone' => '',  'email' => '',  'lottery_number' => '70',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'MARG HAWKINS',  'telephone' => '',  'email' => '',  'lottery_number' => '71',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'PAT IMRIE',  'telephone' => '',  'email' => '',  'lottery_number' => '71',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'PAT GOODING',  'telephone' => '0188438048',  'email' => 'patrick.gooding@hotmail.co.uk',  'lottery_number' => '72',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'ANDREA MADDOCKS',  'telephone' => '01252319939',  'email' => 'bpandammaddock@virginmedia.com',  'lottery_number' => '72',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'ALISON WIDGERY',  'telephone' => '07584778565',  'email' => '',  'lottery_number' => '73',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'ANN FEETENBY',  'telephone' => '01723581239',  'email' => 'annfeetenby@hotmail.com',  'lottery_number' => '73',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'REBECCA WESTALL',  'telephone' => '0188438883',  'email' => 'rrwestall16@yahoo.co.uk',  'lottery_number' => '74',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'MEL ELLIOTT',  'telephone' => '07990995122',  'email' => 'hairgelmel@hotmail.co.uk',  'lottery_number' => '74',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'MARGARET SIVITER',  'telephone' => '',  'email' => '',  'lottery_number' => '75',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'PAT IMRIE',  'telephone' => '',  'email' => '',  'lottery_number' => '75',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'MIKE BROOM',  'telephone' => '',  'email' => '',  'lottery_number' => '76',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'STACEY EVERETT',  'telephone' => '07946845061',  'email' => 'stacey.everett484@live.co.uk',  'lottery_number' => '76',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'SHIRLEY BOYCE',  'telephone' => '',  'email' => '',  'lottery_number' => '77',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'STACEY EVERETT',  'telephone' => '07946845061',  'email' => 'stacey.everett484@live.co.uk',  'lottery_number' => '77',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'DAVID PALFREY',  'telephone' => '0188434263',  'email' => 'ritandavid@talktalk.net',  'lottery_number' => '78',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'MAXINE CRAWFORD',  'telephone' => '',  'email' => '',  'lottery_number' => '78',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'MALCOLM SMITH',  'telephone' => '',  'email' => '',  'lottery_number' => '79',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'ANN FEETENBY',  'telephone' => '01723581239',  'email' => 'annfeetenby@hotmail.com',  'lottery_number' => '79',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'CHLOE',  'telephone' => '',  'email' => '',  'lottery_number' => '80',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'ANN FEETENBY',  'telephone' => '01723581239',  'email' => 'annfeetenby@hotmail.com',  'lottery_number' => '80',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'PHIL JAMES',  'telephone' => '',  'email' => '',  'lottery_number' => '81',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'LINDA SHAW',  'telephone' => '07745498789',  'email' => 'l.shaw65@btinternet.com',  'lottery_number' => '81',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'DAVID PALFREY',  'telephone' => '0188434263',  'email' => 'ritandavid@talktalk.net',  'lottery_number' => '82',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'JULIE LE CORNU',  'telephone' => '07969461883',  'email' => 'jules.11@hotmail.co.uk',  'lottery_number' => '82',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'MAT NEWELL',  'telephone' => '07809261574',  'email' => 'mat710@hotmail.co.uk',  'lottery_number' => '83',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'AXEL FOLEY',  'telephone' => '',  'email' => 'axel@trenchartax.com',  'lottery_number' => '83',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'MARGARET SIVITER',  'telephone' => '',  'email' => '',  'lottery_number' => '84',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'PAMELA CRAWFORD',  'telephone' => '',  'email' => '',  'lottery_number' => '84',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'GAIL JONES',  'telephone' => '07835473810',  'email' => 'k9services@gmx.com',  'lottery_number' => '85',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'KEVIN CAHALIN',  'telephone' => '07938124621',  'email' => '',  'lottery_number' => '85',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'TRISHA PARTRIDGE',  'telephone' => '',  'email' => '',  'lottery_number' => '86',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'JULIE LE CORNU',  'telephone' => '07969461883',  'email' => 'jules.11@hotmail.co.uk',  'lottery_number' => '86',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'MARTIN COFFEY',  'telephone' => '0188432943',  'email' => '',  'lottery_number' => '87',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'MARY KENNEDY',  'telephone' => '07749049622',  'email' => 'mary.keneddy12@btinternet.com',  'lottery_number' => '87',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'PHIL JAMES',  'telephone' => '',  'email' => '',  'lottery_number' => '88',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'MEL ELLIOTT',  'telephone' => '',  'email' => '',  'lottery_number' => '88',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'IAN ATKINS',  'telephone' => '07731691020',  'email' => '',  'lottery_number' => '89',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'MEL ELLIOTT',  'telephone' => '',  'email' => '',  'lottery_number' => '89',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'DAPHNE ATKINS',  'telephone' => '0NOT GIVEN',  'email' => '',  'lottery_number' => '90',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'ELAIN FAIRLEY',  'telephone' => '01606835535',  'email' => 'elainefairley@talktalk.net',  'lottery_number' => '90',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'PHIL JAMES',  'telephone' => '',  'email' => '',  'lottery_number' => '91',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'ANN FEETENBY',  'telephone' => '01723581239',  'email' => 'annfeetenby@hotmail.com',  'lottery_number' => '91',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'PHIL JAMES',  'telephone' => '',  'email' => '',  'lottery_number' => '92',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'LOUISE CARTER',  'telephone' => '07708392349',  'email' => 'louise.carter@hotmail.co.uk',  'lottery_number' => '92',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'MARTIN COFFEY',  'telephone' => '',  'email' => '',  'lottery_number' => '93',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'SARAH RADAR O\'CONNOR',  'telephone' => '07521156348',  'email' => 'hercules179@goodlemail.com',  'lottery_number' => '93',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'ADRIAN HUMMING',  'telephone' => '0188434834',  'email' => 'a-hemming@sky.com',  'lottery_number' => '94',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'ANDREA MADDOCKS',  'telephone' => '01252319939',  'email' => 'bpandammaddock@virginmedia.com',  'lottery_number' => '94',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'T PRING',  'telephone' => '0188433475',  'email' => 'tlpring@aol.com',  'lottery_number' => '95',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'LOUISE CARTER',  'telephone' => '07708392349',  'email' => 'louise.carter@hotmail.co.uk',  'lottery_number' => '95',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'PENNY HUTTER',  'telephone' => '0188434423',  'email' => 'PENNY.HUTTER@BTINTERNET.COM',  'lottery_number' => '96',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'MEL ELLIOTT',  'telephone' => '',  'email' => '',  'lottery_number' => '96',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'MRS T MAUNDER',  'telephone' => '01884841053',  'email' => '',  'lottery_number' => '97',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'LOUISE CARTER',  'telephone' => '07708392349',  'email' => 'louise.carter@hotmail.co.uk',  'lottery_number' => '97',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'TINA VAUGHN',  'telephone' => '',  'email' => '',  'lottery_number' => '98',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'ALLAN KNIGHT',  'telephone' => '07429669442',  'email' => 'ciknights@aol.com',  'lottery_number' => '98',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'HAZEL VINNICOMBE',  'telephone' => '0188433681',  'email' => '',  'lottery_number' => '99',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'LIZ MACHIN',  'telephone' => '07592349291',  'email' => 'lizcorney@btinternet.com',  'lottery_number' => '99',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'DAVID SPEARS',  'telephone' => '',  'email' => 'dspeirs9@mypostoffice.co.uk',  'lottery_number' => '100',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'LIZ MACHIN',  'telephone' => '07592349291',  'email' => 'lizcorney@btinternet.com',  'lottery_number' => '100',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'GILLIAN PENGELLY',  'telephone' => '01884266719',  'email' => 'johngilly@tiscali.co.uk',  'lottery_number' => '101',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'KATE HILL',  'telephone' => '',  'email' => '',  'lottery_number' => '101',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'MRS T MAUNDER',  'telephone' => '01884841053',  'email' => '',  'lottery_number' => '102',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'SHARON CROOK',  'telephone' => '',  'email' => '',  'lottery_number' => '102',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'VITAMIN C',  'telephone' => '',  'email' => '',  'lottery_number' => '103',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'SHARON CROOK',  'telephone' => '',  'email' => '',  'lottery_number' => '103',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'MRS T MAUNDER',  'telephone' => '01884841053',  'email' => '',  'lottery_number' => '104',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'LISA BILLING ',  'telephone' => '07707734562',  'email' => 'lisawade@gmx.com',  'lottery_number' => '104',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'JIM MYERS',  'telephone' => '',  'email' => '',  'lottery_number' => '105',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'CAROL JONES',  'telephone' => '',  'email' => '',  'lottery_number' => '105',  'draw_type' => 'UK']);
		LotteryPlayer::create([ 'name' => 'BETTY CARROTT',  'telephone' => '0188435518',  'email' => 'bettycarrott@live.co.uk',  'lottery_number' => '106',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'SALLY WESTALL',  'telephone' => '07864565114',  'email' => 'ssllywestall202@btinternet.com',  'lottery_number' => '107',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'KEVIN WESTALL',  'telephone' => '07704064480',  'email' => 'ssllywestall202@btinternet.com',  'lottery_number' => '108',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'SANDRA ROBEZNIECE',  'telephone' => '07746399354',  'email' => '',  'lottery_number' => '109',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'RYAN COFFEY',  'telephone' => '',  'email' => '',  'lottery_number' => '110',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'NICK LUSH',  'telephone' => '',  'email' => 'nick_kopite@hotmail.co.uk',  'lottery_number' => '111',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'ELIZABETH STOYLE',  'telephone' => '07544518012',  'email' => 'thebazile63@sky.com',  'lottery_number' => '112',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'NICK LUSH',  'telephone' => '',  'email' => '',  'lottery_number' => '113',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'LYNNETTE  FRAYNE',  'telephone' => '0188433552',  'email' => '',  'lottery_number' => '114',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'SPENCER STOYLE',  'telephone' => '07735429258',  'email' => 'worlfoftwist71@sky.com',  'lottery_number' => '115',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'CARA FUDGE',  'telephone' => '01884798180',  'email' => 'fudgeswoolandhaberdashery@gmail.com',  'lottery_number' => '116',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'HAYLEY ROBERTS-PALMER',  'telephone' => '01884560430',  'email' => '',  'lottery_number' => '117',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'CLAIRE TRUMAN',  'telephone' => '0 ',  'email' => 'crewealexbabe@hotmail.com',  'lottery_number' => '118',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'PHIL JAMES',  'telephone' => '',  'email' => '',  'lottery_number' => '119',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'SIMON ATKINS',  'telephone' => '07503451441',  'email' => 'simonatkims57@gmail.com',  'lottery_number' => '120',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'SIMON ATKINS',  'telephone' => '07503451441',  'email' => 'simonatkims57@gmail.com',  'lottery_number' => '121',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'KATH ROWSELL',  'telephone' => '0188438996',  'email' => 'k.rowsell51@btinternet.com',  'lottery_number' => '122',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'ANTHONY GARRETT',  'telephone' => '',  'email' => '',  'lottery_number' => '123',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'DAVID WADDILAND',  'telephone' => '',  'email' => '',  'lottery_number' => '124',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'SAMANTHA LANE',  'telephone' => '07803484614',  'email' => 'N0NE',  'lottery_number' => '125',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'TONY ANDREWS',  'telephone' => '07967013253',  'email' => '',  'lottery_number' => '126',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'ALISON FLEMING',  'telephone' => '01363776468',  'email' => 'ampf28@live.co.uk',  'lottery_number' => '127',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'BRIDGET DREW',  'telephone' => '01392363871',  'email' => 'bridgetd@uwclub.net',  'lottery_number' => '128',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'SHIRLEY BOYCE',  'telephone' => '',  'email' => '',  'lottery_number' => '129',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'ALISON FLEMING',  'telephone' => '01363776468',  'email' => 'ampf28@live.co.uk',  'lottery_number' => '130',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'JOHN STOCKMAN',  'telephone' => '01392882129',  'email' => ' ',  'lottery_number' => '131',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'DENNIS PITTS',  'telephone' => '01392861754',  'email' => '',  'lottery_number' => '132',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'KATH ROWSELL',  'telephone' => '',  'email' => '',  'lottery_number' => '133',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'JOHN TRUMAN',  'telephone' => '',  'email' => '',  'lottery_number' => '134',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'SEAN POWER',  'telephone' => '',  'email' => '',  'lottery_number' => '135',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'KATH ROWSELL',  'telephone' => '',  'email' => '',  'lottery_number' => '136',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'WENDY POWER',  'telephone' => '0 ',  'email' => '',  'lottery_number' => '137',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'SHIRLEY BOYCE',  'telephone' => '',  'email' => '',  'lottery_number' => '138',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'SHIRLEY BOYCE',  'telephone' => '',  'email' => '',  'lottery_number' => '139',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'KATH ROWSELL',  'telephone' => '',  'email' => '',  'lottery_number' => '140',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'MARK STEVENS',  'telephone' => '',  'email' => '',  'lottery_number' => '141',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'BECKY DENNIS',  'telephone' => '',  'email' => '',  'lottery_number' => '142',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'MRS JOAN MARSHALL',  'telephone' => '0188434871',  'email' => '',  'lottery_number' => '143',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'BECKY DENNIS',  'telephone' => '',  'email' => '',  'lottery_number' => '144',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'SANDRA PARRAMORE',  'telephone' => '0     O188435516',  'email' => '',  'lottery_number' => '145',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'JULIE PARKER',  'telephone' => '07878482411',  'email' => 'jewbags@icloud.com',  'lottery_number' => '146',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'TIFF HORTON',  'telephone' => '',  'email' => '',  'lottery_number' => '147',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'JOANNE RUDDY',  'telephone' => '0188434879',  'email' => 'joanna.ruddy@yahoo.co.uk',  'lottery_number' => '148',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'DANIEL KEMP',  'telephone' => '',  'email' => '',  'lottery_number' => '149',  'draw_type' => 'Local']);
		LotteryPlayer::create([ 'name' => 'SUE LAWSON',  'telephone' => '01392881431',  'email' => 'susan101lawson@btinternet.com',  'lottery_number' => '150',  'draw_type' => 'Local']);
    }
}